### ISSUE TITLE
PAHAHAHAHA

### ISSUE THREAD

**Issue by MistressPlague** [Lucario4LyfeYT/RAFLAB#1]
weak

**Comment by Lucario4LyfeYT** [comment]
Working on a fix for that problem right now, thanks for pointing that out!

**Comment by MistressPlague** [comment]
Good luck, you will definitely need it. Much smarter than you have already tried to effect actual antirips.

**Comment by Lucario4LyfeYT** [comment]
A fix has been administered to your issue sir, have a good day/night.
